### ISSUE TITLE
Double quotes are replacing single quotes on save

### ISSUE THREAD

**Issue by dan-mckay** [prettier/prettier-atom#204] opened 2017-06-22 13:12 UTC
I have this configuration in Settings:
![screen shot 2017-06-22 at 14 05 49](https://user-images.githubusercontent.com/1457201/27435454-326b8552-5754-11e7-945f-ab231a920b3a.png)
...but every time a save a js file, the single quotes are being replaced by double quotes. It is a recent issue and also affects my colleague in the same way. I am running v0.34.0 of the package and v1.18.0 of Atom.

Any thoughts/solutions?

**Comment by darahak** [comment] 2017-06-22 23:12
I can't reproduce the issue.

Can you publish your config displayed by command `prettier:debug` and also give us an example so we can have more context?

**Comment by jameswyse** [comment] 2017-07-02 07:01
I'm having the same issue. They also show up as linter errors:

<img width="660" alt="screen shot 2017-07-02 at 4 59 29 pm" src="https://user-images.githubusercontent.com/1144357/27767851-f3983ec8-5f47-11e7-9446-2ce809bdfd0b.png">

prettier:debug output:

```
Atom version: 1.18.0
prettier-atom version: undefined
prettier version: undefined
prettier-eslint version: undefined
prettier-atom configuration: {
  "formatOnSaveOptions": {
    "enabled": true,
    "respectEslintignore": true,
    "showInStatusBar": false,
    "javascriptScopes": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.babel",
      "source.js-semantic",
      "text.html.basic",
      "text.html.vue"
    ],
    "typescriptScopes": [
      "source.ts",
      "source.tsx",
      "source.ts.tsx"
    ],
    "cssScopes": [
      "source.css",
      "source.less",
      "source.css.less",
      "source.scss",
      "source.css.scss"
    ],
    "jsonScopes": [
      "source.json"
    ],
    "excludedGlobs": [],
    "whitelistedGlobs": [],
    "isDisabledIfNotInPackageJson": false
  },
  "prettierOptions": {
    "singleQuote": true,
    "bracketSpacing": true,
    "semi": true,
    "useTabs": false,
    "jsxBracketSameLine": false,
    "printWidth": 80,
    "tabWidth": "auto",
    "trailingComma": "none",
    "parser": "babylon"
  },
  "useEslint": true,
  "silenceErrors": false,
  "useEditorConfig": true,
  "prettierEslintOptions": {
    "prettierLast": false
  }
}
```

**Comment by robwise** [comment] 2017-07-08 19:37
I am going to close this for now, please let me know if there is still something that needs to be addressed and I will reopen.

**Closed by robwise** 2017-07-08 19:37 UTC
Labels: question

**Comment by sunny-mittal** [comment] 2018-04-09 00:16
I'm having the same issue. Here's the debug information that's printed:
```
  ...
  "prettierOptions": {
    "semi": false,
    "singleQuote": true,
    "bracketSpacing": true,
    "useTabs": false,
    "jsxBracketSameLine": false,
    "printWidth": 80,
    "tabWidth": "auto",
    "trailingComma": "none",
    "parser": "babylon",
    "arrowParens": "avoid"
  },
```
and running `yarn prettier src/index.ts` uses the correct quotes. Any help would be much appreciated.

**Comment by mikeebee** [comment] 2018-09-26 01:54
Hi there, 

I'm having a similar issue with single quotes in package settings. I've noticed it when it was a bare bones project and I didn't have any ESLint `.eslintrc` or Prettier `.prettierrc` configs in place. This is when I would assume the package defaults would prevail.

This is my Prettier debug info...

```
Atom version: 1.21.2
prettier-atom version: 0.55.2
prettier: bundled
prettier version: 1.13.4
prettier-eslint version: 8.8.2
prettier-atom configuration: {
  "formatOnSaveOptions": {
    "enabled": true,
    "showInStatusBar": true,
    "respectEslintignore": true,
    "excludedGlobs": [],
    "whitelistedGlobs": [],
    "isDisabledIfNotInPackageJson": false,
    "isDisabledIfNoConfigFile": false
  },
  "prettierOptions": {
    "jsxBracketSameLine": true,
    "printWidth": 120,
    "singleQuote": true
  },
  "useEslint": true,
  "useStylelint": false,
  "prettierEslintOptions": {
    "prettierLast": false
  }
}
```

I tried changing the `useEslint` option but nothing changed.

In addition, I added a `.prettierrc` file with these options which were also ignored...

```
{
  "semi": false,
  "singleQuote": true
}

```

I feel like there is something simple I'm doing wrong! Would be good to hear your thoughts.

Many thanks

**Comment by robwise** [comment] 2018-09-26 04:05
@mikeebee There is an annoying Atom bug that leaves options that were deleted in a newer version of a package inside of your config. prettier-atom actual prettier settings no longer can be configured from within prettier-atom. You must use a .prettierrc (either a global one in your home directory or on a per-project basis).

Please make sure to restart Atom after adding a `.prettierrc` as the lookup is cached for performance reasons.

**Comment by mikeebee** [comment] 2018-09-26 04:09
Aaah! I wondered why there were so few options. That makes sense and a restart has the `.prettierrc` file working perfectly. 

Thanks for clarifying.
