### ISSUE TITLE
'Only format' options disable formatting on save

### ISSUE THREAD

**Issue by SavePointSam** [prettier/prettier-atom#360] opened 2018-01-30 06:41 UTC
Based on the conversation from #289, when enabling 'only format' type options disables formatting on save.

Not much else is known about this particular issue, though I have seen it myself as well.

**Comment by robwise** [comment] 2018-01-30 08:12
Might we just want to move over to checking the node modules instead? Although, that might have its own problems, such as for people who for whatever reason have put their node modules folders in unexpected places.

The related issue for that is https://github.com/prettier/prettier-atom/issues/191

**Comment by leepowellcouk** [comment] 2018-02-05 10:45
Discovered this morning that 'Format on save' begins working when I disable the ESLint Integration.

**Comment by leepowellcouk** [comment] 2018-02-05 10:46
Discovered this morning that 'Format on Save' beings working when I disable ESLint Integration.

**Comment by SavePointSam** [comment] 2018-02-05 14:59
Thanks for the update! We do have some fallback logic to another package when you enable this feature. Maybe there is an issue on their end? Maybe we need to update our internal version?

**Comment by mikestopcontinues** [comment] 2018-03-08 09:24
I'm not sure if this is related, but I could only get format-on-save working if "Only format if a Prettier config is found" was disabled... I use a "prettier" key in my package.json. Options I set there do affect results when running in the terminal.

**Comment by brettdewoody** [comment] 2018-03-23 12:44
Same solution as @mikestopcontinues. I have a `prettier` key in `package.json`. With the 'Only format if Prettier is found in your project's dependencies' enabled, Prettier does not format on save. When I disable that option, and have 'Only format if a Prettier config is found' enabled, Prettier formats on save.

**Comment by olsonpm** [comment] 2018-03-23 14:20
if you post a sample github repo reproducing your issue I will look into the cause of this @brettdewoody

**Comment by robwise** [comment] 2018-08-20 17:59
This should probably be fixed in #404

**Closed by robwise** 2018-08-20 17:59 UTC
Labels: bug
