### ISSUE TITLE
change from ' to " all the times

### ISSUE THREAD

**Issue by yuber83** [prettier/prettier-atom#452] opened 2018-09-02 02:55 UTC
All the time change from single quote  ' to double quote "
But when i need to specify a string, i prefer to use single quotes but prettier-atom
makes me difficult to work.
I use Debian GNU/Linux 9.5 (stretch)
atom 1.29.0 x64
and prettier-atom 0.55.2

and i changed  Prettier-atom Options
Prettier Options
Prettier Options single Quote 
but nothing happen.

i declare:

const foo = 'ejemplo1';
and prettier change to this
const foo = "ejemplo1";

**Comment by robwise** [comment] 2018-09-03 10:54
duplicate of https://github.com/prettier/prettier-atom/issues/449

**Closed by robwise** 2018-09-03 10:54 UTC
