### ISSUE TITLE
Cannot read property 'range' of null when using ES6 string concatenation

### ISSUE THREAD

**Issue by Danman7** [prettier/prettier-atom#443] opened 2018-08-22 06:45 UTC
I am developing a [react-static](https://github.com/nozzle/react-static) app on Atom with Babel. Every time I'm editing a `jsx` file and use something of the sort of
```
`string-${variable}` 
```
the linter highlights the first line of the file, ignores all other linting errors and I get a `prettier-atom failed: Cannot read property 'range' of null` error. I'm not entirely sure the problem is with prettier-atom and believe I'm doing something wrong in the setup.

This is my `.eslintrc.js`:
```
module.exports = {
  extends: [
    'react-tools',
    'plugin:import/errors',
    'plugin:import/warnings',
    'plugin:jest/recommended',
  ],
  plugins: ['jest', 'import'],
  env: {
    'jest/globals': true,
  },
  rules: {
    'import/no-unresolved': [2, { ignore: ['react-static-routes'] }],
  },
}
```

My `.babelrc`:

```
{
  "extends": "react-static/.babelrc",
  "plugins": ["babel-plugin-styled-components", "react-hot-loader/babel"]
}
```

And my `Prettier: Debug` result:
```
Atom version: 1.29.0
prettier-atom version: 0.55.1
prettier: bundled
prettier version: 1.13.4
prettier-eslint version: 8.8.2
prettier-atom configuration: {
  "formatOnSaveOptions": {
    "enabled": true,
    "showInStatusBar": true,
    "respectEslintignore": true,
    "excludedGlobs": [],
    "whitelistedGlobs": [],
    "isDisabledIfNotInPackageJson": false,
    "isDisabledIfNoConfigFile": false
  },
  "prettierEslintOptions": {
    "prettierLast": false
  },
  "prettierOptions": {
    "semi": false,
    "singleQuote": true
  },
  "useEditorConfig": false,
  "useEslint": true,
  "useStylelint": false
}
```

What further information can I provide?

**Comment by robwise** [comment] 2018-08-22 07:31
What would be helpful is if we narrow it down to whether it's a prettier-atom problem or a prettier problem. Can you try running Prettier from the command line and seeing what happens?

**Comment by robwise** [comment] 2018-08-23 01:55
Hmm, probably a prettier-atom error then. Can you show the full stack trace of the error (open console with <kbd>cmd</kbd> <kbd>option</kbd> <kbd>i</kbd>)?

**Comment by Danman7** [comment] 2018-08-23 07:45
I didn't know this was possible. Cool. Does this make sense? I'm not sure how to format it better.

```
/Users/dan/.atom/packages/prettier-atom/node_modules/loglevel-colored-level-prefix/dist/index.js:54 prettier-eslint [ERROR]: eslint fix failed due to an eslint error
(anonymous) @ /Users/dan/.atom/packages/prettier-atom/node_modules/loglevel-colored-level-prefix/dist/index.js:54
eslintFix @ /Users/dan/.atom/packages/prettier-atom/node_modules/prettier-eslint/dist/index.js:204
format @ /Users/dan/.atom/packages/prettier-atom/node_modules/prettier-eslint/dist/index.js:149
allowUnsafeNewFunction @ /Users/dan/.atom/packages/prettier-atom/dist/executePrettier/executePrettierOnBufferRange.js:51
exports.allowUnsafeNewFunction @ /Users/dan/.atom/packages/prettier-atom/node_modules/loophole/lib/loophole.js:25
executePrettierEslint @ /Users/dan/.atom/packages/prettier-atom/dist/executePrettier/executePrettierOnBufferRange.js:51
(anonymous) @ /Users/dan/.atom/packages/prettier-atom/dist/executePrettier/executePrettierOnBufferRange.js:71
step @ /Users/dan/.atom/packages/prettier-atom/node_modules/babel-runtime/helpers/asyncToGenerator.js:17
(anonymous) @ /Users/dan/.atom/packages/prettier-atom/node_modules/babel-runtime/helpers/asyncToGenerator.js:35
F @ /Users/dan/.atom/packages/prettier-atom/node_modules/core-js/library/modules/_export.js:36
(anonymous) @ /Users/dan/.atom/packages/prettier-atom/node_modules/babel-runtime/helpers/asyncToGenerator.js:14
executePrettierOrIntegration @ /Users/dan/.atom/packages/prettier-atom/dist/executePrettier/executePrettierOnBufferRange.js:89
(anonymous) @ /Users/dan/.atom/packages/prettier-atom/dist/executePrettier/executePrettierOnBufferRange.js:108
step @ /Users/dan/.atom/packages/prettier-atom/node_modules/babel-runtime/helpers/asyncToGenerator.js:17
(anonymous) @ /Users/dan/.atom/packages/prettier-atom/node_modules/babel-runtime/helpers/asyncToGenerator.js:35
F @ /Users/dan/.atom/packages/prettier-atom/node_modules/core-js/library/modules/_export.js:36
(anonymous) @ /Users/dan/.atom/packages/prettier-atom/node_modules/babel-runtime/helpers/asyncToGenerator.js:14
executePrettierOnBufferRange @ /Users/dan/.atom/packages/prettier-atom/dist/executePrettier/executePrettierOnBufferRange.js:135
callAppropriatePrettierExecutor @ /Users/dan/.atom/packages/prettier-atom/dist/formatOnSave/index.js:10
n @ /Users/dan/.atom/packages/prettier-atom/node_modules/lodash/lodash.min.js:5
(anonymous) @ /Users/dan/.atom/packages/prettier-atom/node_modules/lodash/lodash.min.js:97
n @ /Users/dan/.atom/packages/prettier-atom/node_modules/lodash/lodash.min.js:5
(anonymous) @ /Users/dan/.atom/packages/prettier-atom/node_modules/lodash/lodash.min.js:63
(anonymous) @ /Users/dan/.atom/packages/prettier-atom/node_modules/lodash/lodash.min.js:49
attemptWithErrorNotification @ /Users/dan/.atom/packages/prettier-atom/dist/formatOnSave/index.js:14
(anonymous) @ /Users/dan/.atom/packages/prettier-atom/dist/atomInterface/index.js:57
step @ /Users/dan/.atom/packages/prettier-atom/node_modules/babel-runtime/helpers/asyncToGenerator.js:17
(anonymous) @ /Users/dan/.atom/packages/prettier-atom/node_modules/babel-runtime/helpers/asyncToGenerator.js:35
F @ /Users/dan/.atom/packages/prettier-atom/node_modules/core-js/library/modules/_export.js:36
(anonymous) @ /Users/dan/.atom/packages/prettier-atom/node_modules/babel-runtime/helpers/asyncToGenerator.js:14
attemptWithErrorNotification @ /Users/dan/.atom/packages/prettier-atom/dist/atomInterface/index.js:65
safeFormatOnSaveIfAppropriate @ /Users/dan/.atom/packages/prettier-atom/dist/formatOnSave/index.js:14
(anonymous) @ /Users/dan/.atom/packages/prettier-atom/dist/main.js:38
step @ /Users/dan/.atom/packages/prettier-atom/node_modules/babel-runtime/helpers/asyncToGenerator.js:17
(anonymous) @ /Users/dan/.atom/packages/prettier-atom/node_modules/babel-runtime/helpers/asyncToGenerator.js:35
F @ /Users/dan/.atom/packages/prettier-atom/node_modules/core-js/library/modules/_export.js:36
(anonymous) @ /Users/dan/.atom/packages/prettier-atom/node_modules/babel-runtime/helpers/asyncToGenerator.js:14
lazyFormatOnSave @ /Users/dan/.atom/packages/prettier-atom/dist/main.js:42
subscriptions.add.editor.getBuffer.onWillSave @ /Users/dan/.atom/packages/prettier-atom/dist/main.js:111
module.exports.Emitter.simpleDispatch @ commitCommentContainer_item.graphql.js:112
(anonymous) @ commitCommentContainer_item.graphql.js:112
module.exports.Emitter.emitAsync @ commitCommentContainer_item.graphql.js:112
(anonymous) @ commitCommentContainer_item.graphql.js:112
Promise resolved (async)
module.exports.TextBuffer.saveTo @ commitCommentContainer_item.graphql.js:112
module.exports.TextBuffer.save @ commitCommentContainer_item.graphql.js:112
save @ commitCommentContainer_item.graphql.js:112
promisify @ commitCommentContainer_item.graphql.js:112
promisify @ commitCommentContainer_item.graphql.js:112
saveItem @ commitCommentContainer_item.graphql.js:112
saveActiveItem @ commitCommentContainer_item.graphql.js:112
saveActivePaneItem @ commitCommentContainer_item.graphql.js:112
core:save @ commitCommentContainer_item.graphql.js:112
handleCommandEvent @ commitCommentContainer_item.graphql.js:112
module.exports.KeymapManager.dispatchCommandEvent @ commitCommentContainer_item.graphql.js:112
module.exports.KeymapManager.handleKeyboardEvent @ commitCommentContainer_item.graphql.js:112
handleDocumentKeyEvent @ commitCommentContainer_item.graphql.js:112
/Users/dan/.atom/packages/prettier-atom/dist/executePrettier/handleError.js:36 TypeError: Cannot read property 'range' of null
    at SourceCode.getTokenBefore (/Users/dan/Desktop/projects/polaris/node_modules/eslint/lib/token-store/index.js:303:18)
    at checkSpacingBefore (/Users/dan/Desktop/projects/polaris/node_modules/eslint/lib/rules/template-curly-spacing.js:52:42)
    at TemplateElement (/Users/dan/Desktop/projects/polaris/node_modules/eslint/lib/rules/template-curly-spacing.js:117:17)
    at listeners.(anonymous function).forEach.listener (/Users/dan/Desktop/projects/polaris/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/dan/Desktop/projects/polaris/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/Users/dan/Desktop/projects/polaris/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/dan/Desktop/projects/polaris/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/Users/dan/Desktop/projects/polaris/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/Users/dan/Desktop/projects/polaris/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at Traverser.enter [as _enter] (/Users/dan/Desktop/projects/polaris/node_modules/eslint/lib/linter.js:865:28)
    at Traverser._traverse (/Users/dan/Desktop/projects/polaris/node_modules/eslint/lib/util/traverser.js:132:14)
    at Traverser._traverse (/Users/dan/Desktop/projects/polaris/node_modules/eslint/lib/util/traverser.js:144:34)
    at Traverser._traverse (/Users/dan/Desktop/projects/polaris/node_modules/eslint/lib/util/traverser.js:147:30)
    at Traverser._traverse (/Users/dan/Desktop/projects/polaris/node_modules/eslint/lib/util/traverser.js:144:34)
    at Traverser._traverse (/Users/dan/Desktop/projects/polaris/node_modules/eslint/lib/util/traverser.js:144:34)
    at Traverser._traverse (/Users/dan/Desktop/projects/polaris/node_modules/eslint/lib/util/traverser.js:147:30)
    at Traverser._traverse (/Users/dan/Desktop/projects/polaris/node_modules/eslint/lib/util/traverser.js:144:34)
    at Traverser._traverse (/Users/dan/Desktop/projects/polaris/node_modules/eslint/lib/util/traverser.js:147:30)
    at Traverser._traverse (/Users/dan/Desktop/projects/polaris/node_modules/eslint/lib/util/traverser.js:147:30)
    at Traverser._traverse (/Users/dan/Desktop/projects/polaris/node_modules/eslint/lib/util/traverser.js:144:34)
    at Traverser._traverse (/Users/dan/Desktop/projects/polaris/node_modules/eslint/lib/util/traverser.js:147:30)
    at Traverser._traverse (/Users/dan/Desktop/projects/polaris/node_modules/eslint/lib/util/traverser.js:144:34)
    at Traverser._traverse (/Users/dan/Desktop/projects/polaris/node_modules/eslint/lib/util/traverser.js:147:30)
    at Traverser._traverse (/Users/dan/Desktop/projects/polaris/node_modules/eslint/lib/util/traverser.js:144:34)
    at Traverser.traverse (/Users/dan/Desktop/projects/polaris/node_modules/eslint/lib/util/traverser.js:115:14)
    at runRules (/Users/dan/Desktop/projects/polaris/node_modules/eslint/lib/linter.js:862:15)
    at Linter._verifyWithoutProcessors (/Users/dan/Desktop/projects/polaris/node_modules/eslint/lib/linter.js:1003:33)
    at preprocess.map.textBlock (/Users/dan/Desktop/projects/polaris/node_modules/eslint/lib/linter.js:1046:35)
    at Array.map (<anonymous>)
displayErrorInPopup @ /Users/dan/.atom/packages/prettier-atom/dist/executePrettier/handleError.js:36
n @ /Users/dan/.atom/packages/prettier-atom/node_modules/lodash/lodash.min.js:5
(anonymous) @ /Users/dan/.atom/packages/prettier-atom/node_modules/lodash/lodash.min.js:97
n @ /Users/dan/.atom/packages/prettier-atom/node_modules/lodash/lodash.min.js:5
(anonymous) @ /Users/dan/.atom/packages/prettier-atom/node_modules/lodash/lodash.min.js:63
(anonymous) @ /Users/dan/.atom/packages/prettier-atom/node_modules/lodash/lodash.min.js:49
(anonymous) @ /Users/dan/.atom/packages/prettier-atom/dist/executePrettier/executePrettierOnBufferRange.js:110
step @ /Users/dan/.atom/packages/prettier-atom/node_modules/babel-runtime/helpers/asyncToGenerator.js:17
(anonymous) @ /Users/dan/.atom/packages/prettier-atom/node_modules/babel-runtime/helpers/asyncToGenerator.js:30
Promise rejected (async)
step @ /Users/dan/.atom/packages/prettier-atom/node_modules/babel-runtime/helpers/asyncToGenerator.js:27
(anonymous) @ /Users/dan/.atom/packages/prettier-atom/node_modules/babel-runtime/helpers/asyncToGenerator.js:35
F @ /Users/dan/.atom/packages/prettier-atom/node_modules/core-js/library/modules/_export.js:36
(anonymous) @ /Users/dan/.atom/packages/prettier-atom/node_modules/babel-runtime/helpers/asyncToGenerator.js:14
executePrettierOnBufferRange @ /Users/dan/.atom/packages/prettier-atom/dist/executePrettier/executePrettierOnBufferRange.js:135
callAppropriatePrettierExecutor @ /Users/dan/.atom/packages/prettier-atom/dist/formatOnSave/index.js:10
n @ /Users/dan/.atom/packages/prettier-atom/node_modules/lodash/lodash.min.js:5
(anonymous) @ /Users/dan/.atom/packages/prettier-atom/node_modules/lodash/lodash.min.js:97
n @ /Users/dan/.atom/packages/prettier-atom/node_modules/lodash/lodash.min.js:5
(anonymous) @ /Users/dan/.atom/packages/prettier-atom/node_modules/lodash/lodash.min.js:63
(anonymous) @ /Users/dan/.atom/packages/prettier-atom/node_modules/lodash/lodash.min.js:49
attemptWithErrorNotification @ /Users/dan/.atom/packages/prettier-atom/dist/formatOnSave/index.js:14
(anonymous) @ /Users/dan/.atom/packages/prettier-atom/dist/atomInterface/index.js:57
step @ /Users/dan/.atom/packages/prettier-atom/node_modules/babel-runtime/helpers/asyncToGenerator.js:17
(anonymous) @ /Users/dan/.atom/packages/prettier-atom/node_modules/babel-runtime/helpers/asyncToGenerator.js:35
F @ /Users/dan/.atom/packages/prettier-atom/node_modules/core-js/library/modules/_export.js:36
(anonymous) @ /Users/dan/.atom/packages/prettier-atom/node_modules/babel-runtime/helpers/asyncToGenerator.js:14
attemptWithErrorNotification @ /Users/dan/.atom/packages/prettier-atom/dist/atomInterface/index.js:65
safeFormatOnSaveIfAppropriate @ /Users/dan/.atom/packages/prettier-atom/dist/formatOnSave/index.js:14
(anonymous) @ /Users/dan/.atom/packages/prettier-atom/dist/main.js:38
step @ /Users/dan/.atom/packages/prettier-atom/node_modules/babel-runtime/helpers/asyncToGenerator.js:17
(anonymous) @ /Users/dan/.atom/packages/prettier-atom/node_modules/babel-runtime/helpers/asyncToGenerator.js:35
F @ /Users/dan/.atom/packages/prettier-atom/node_modules/core-js/library/modules/_export.js:36
(anonymous) @ /Users/dan/.atom/packages/prettier-atom/node_modules/babel-runtime/helpers/asyncToGenerator.js:14
lazyFormatOnSave @ /Users/dan/.atom/packages/prettier-atom/dist/main.js:42
subscriptions.add.editor.getBuffer.onWillSave @ /Users/dan/.atom/packages/prettier-atom/dist/main.js:111
module.exports.Emitter.simpleDispatch @ commitCommentContainer_item.graphql.js:112
(anonymous) @ commitCommentContainer_item.graphql.js:112
module.exports.Emitter.emitAsync @ commitCommentContainer_item.graphql.js:112
(anonymous) @ commitCommentContainer_item.graphql.js:112
Promise resolved (async)
module.exports.TextBuffer.saveTo @ commitCommentContainer_item.graphql.js:112
module.exports.TextBuffer.save @ commitCommentContainer_item.graphql.js:112
save @ commitCommentContainer_item.graphql.js:112
promisify @ commitCommentContainer_item.graphql.js:112
promisify @ commitCommentContainer_item.graphql.js:112
saveItem @ commitCommentContainer_item.graphql.js:112
saveActiveItem @ commitCommentContainer_item.graphql.js:112
saveActivePaneItem @ commitCommentContainer_item.graphql.js:112
core:save @ commitCommentContainer_item.graphql.js:112
handleCommandEvent @ commitCommentContainer_item.graphql.js:112
module.exports.KeymapManager.dispatchCommandEvent @ commitCommentContainer_item.graphql.js:112
module.exports.KeymapManager.handleKeyboardEvent @ commitCommentContainer_item.graphql.js:112
handleDocumentKeyEvent @ commitCommentContainer_item.graphql.js:112
```

**Comment by robwise** [comment] 2018-08-23 21:17
Oh this is coming out of prettier-eslint. Can you try running prettier-eslint from the command line as opposed to Prettier directly? It might be an issue with that repo.

**Comment by Danman7** [comment] 2018-09-04 09:45
I think I don't understand your request as I believe I already did this: `Running prettier path/to/file in command line returns no errors`

**Comment by robwise** [comment] 2018-09-04 10:19
Don't run prettier, run [prettier-eslint](https://github.com/prettier/prettier-eslint), it's a different tool and it's the one that's throwing the stack trace because you've got ESLint integration turned on. So running vanilla Prettier from the command line isn't correct.

**Comment by cesargdm** [comment] 2018-11-22 03:09
Same issue:
<img width="1166" alt="screen shot 2018-11-21 at 9 08 54 pm" src="https://user-images.githubusercontent.com/10179494/48879502-a95a1100-edd1-11e8-966a-a5f04e89ef8d.png">

**Comment by robwise** [comment] 2018-11-27 17:35
Same response

**Comment by robwise** [comment] 2019-02-15 05:47
Just to clarify, I'm saying that this is a prettier-eslint error, not a prettier or prettier-atom error.

I am going to close this for now, please let me know if there is still something that needs to be addressed and I will reopen.

**Closed by robwise** 2019-02-15 05:47 UTC
Labels: troubleshooting

**Comment by zhengxiaoyao0716** [comment] 2019-05-22 08:35
I reproduce just by use `null as Xxx` syntax.
``` typescript
const test = null as number;

```
It throw `Cannot read property 'range' of null`.

**Comment by fatfatson** [comment] 2019-06-14 16:04
> I reproduce just by use `xxx as Xxx` syntax.
> 
> ```ts
> const test = null as number;
> ```
> 
> It throw `Cannot read property 'range' of null`.

the same problem!
I'm using `@typescript-eslint/parser`,
`eslint file.tsx --fix` in terminal works correctly,
but save in vscode fails to fix the source.
