### ISSUE TITLE
Parser overrrides

### ISSUE THREAD

**Issue by amk221** [prettier/prettier-atom#613] opened 2019-12-09 14:43 UTC
With the following configuration file:

```
module.exports = {
  overrides: [{
    files: '*.hbs',
    options: {
      parser: 'glimmer'
    }
  }]
};
```

`shouldFormatOnSave` is returning false.

...this is because one its conditions is returning false: `doesFileInfoIndicateFormattable`.

...and this is because Prettier's `getFileInfo` is returning the `inferredParser` as `null`.

<hr>

Even if you set `Include (list of globs)` to include `*.hbs` the issue remains.

Notice however that `cmd+p` → `Format` _does_ work.

So, I'm not sure what the difference is between the two (Format on Save and `cmd+p` → Format). But it feels like they should be aligned somehow.

I'm happy to have a go at fixing with some guidance

Possible duplicate: https://github.com/prettier/prettier-atom/issues/500

**Comment by robwise** [comment] 2019-12-09 23:28
It's actually a dupe of this one: https://github.com/prettier/prettier-atom/issues/556

**Closed** 2019-12-09 23:29 UTC
Labels: duplicate

**Comment by amk221** [comment] 2019-12-10 08:48
Thanks
