### ISSUE TITLE
Prettierignored files being formatted.

### ISSUE THREAD

**Issue by conartist6** [prettier/prettier-atom#477] opened 2018-12-11 22:03 UTC
Format-on-saves files which are .prettierignored. No combination of settings will get it to stop.

prettier-atom 0.55.2

prettier@1.14.3 installed as a dev dependency.

**Comment by robwise** [comment] 2018-12-14 03:07
@conartist6 I'm not able to reproduce locally. If you call prettier directly from the command line, does this still happen?

**Comment by robwise** [comment] 2019-02-15 05:44
I am going to close this for now, please let me know if there is still something that needs to be addressed and I will reopen.

**Closed by robwise** 2019-02-15 05:44 UTC
Labels: troubleshooting
