### ISSUE TITLE
Could not format file, error in the console

### ISSUE THREAD

**Issue by yuchi** [prettier/prettier-atom#365] opened 2018-02-02 11:38 UTC
This morning I updated to the latest version of the plugin.

When I try to format I get the following error in the dev console:

```
Uncaught (in promise) TypeError: newText.replace is not a function
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:671:35)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:662:32
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:941:24)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:660:27)
    at TextEditor.setTextInBufferRange (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1307:35)
    at _callee2$ (/Users/pier/.atom/packages/prettier-atom/dist/executePrettier/executePrettierOnBufferRange.js:176:22)
    at tryCatch (/Users/pier/.atom/packages/prettier-atom/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/pier/.atom/packages/prettier-atom/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/pier/.atom/packages/prettier-atom/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/pier/.atom/packages/prettier-atom/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/pier/.atom/packages/prettier-atom/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
```

_Prettier: Debug_ output:

<details>

```
Atom version: 1.23.3
prettier-atom version: 0.49.1
prettier version: 1.10.2
prettier-eslint version: 8.8.1
prettier-atom configuration: {
  "formatOnSaveOptions": {
    "showInStatusBar": true,
    "enabled": false,
    "respectEslintignore": true,
    "javascriptScopes": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.babel",
      "source.js-semantic",
      "text.html.basic",
      "text.html.vue"
    ],
    "typescriptScopes": [
      "source.ts",
      "source.tsx",
      "source.ts.tsx"
    ],
    "cssScopes": [
      "source.css",
      "source.less",
      "source.css.less",
      "source.scss",
      "source.css.scss",
      "source.css.postcss"
    ],
    "jsonScopes": [
      "source.json"
    ],
    "graphQlScopes": [
      "source.graphql"
    ],
    "markdownScopes": [
      "source.md",
      "source.gfm",
      "text.md"
    ],
    "vueScopes": [
      "text.html.vue"
    ],
    "excludedGlobs": [],
    "whitelistedGlobs": [],
    "isDisabledIfNotInPackageJson": false,
    "isDisabledIfNoConfigFile": false
  },
  "prettierOptions": {
    "singleQuote": true,
    "tabWidth": 2,
    "bracketSpacing": true,
    "semi": true,
    "useTabs": false,
    "jsxBracketSameLine": false,
    "printWidth": 80,
    "trailingComma": "none",
    "parser": "babylon",
    "arrowParens": "avoid"
  },
  "useEslint": false,
  "useStylelint": false,
  "useEditorConfig": true,
  "prettierEslintOptions": {
    "prettierLast": false
  }
}
```

</details>

**Comment by SavePointSam** [comment] 2018-02-02 14:44
Closing as this is a duplicate of https://github.com/prettier/prettier-atom/issues/364. Thank you for reporting! I’ve posted a temporary fix in that thread until we can get a fixed build out later today. Apologies for the errors, I understand how frustrating it can be. 💙

**Closed** 2018-02-02 14:44 UTC
Labels: duplicate
