### ISSUE TITLE
Format on Save Not Working

### ISSUE THREAD

**Issue by JuarezLopesJr** [prettier/prettier-atom#366] opened 2018-02-02 14:35 UTC
Format on saving is not working, after upgrade to 0.49.1, i'm running Atom in Debian 9 64bit.
Atom version: 1.23.1
prettier-atom version: 0.49.1
prettier version: 1.10.2
prettier-eslint version: 8.8.1
prettier-atom configuration: {
  "formatOnSaveOptions": {
    "enabled": true,
    "respectEslintignore": true,
    "showInStatusBar": false,
    "javascriptScopes": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.babel",
      "source.js-semantic",
      "text.html.basic",
      "text.html.vue"
    ],
    "typescriptScopes": [
      "source.ts",
      "source.tsx",
      "source.ts.tsx"
    ],
    "cssScopes": [
      "source.css",
      "source.less",
      "source.css.less",
      "source.scss",
      "source.css.scss",
      "source.css.postcss"
    ],
    "jsonScopes": [
      "source.json"
    ],
    "graphQlScopes": [
      "source.graphql"
    ],
    "markdownScopes": [
      "source.md",
      "source.gfm",
      "text.md"
    ],
    "vueScopes": [
      "text.html.vue"
    ],
    "excludedGlobs": [],
    "whitelistedGlobs": [],
    "isDisabledIfNotInPackageJson": false,
    "isDisabledIfNoConfigFile": false
  },
  "prettierOptions": {
    "singleQuote": true,
    "bracketSpacing": true,
    "semi": true,
    "useTabs": false,
    "jsxBracketSameLine": false,
    "printWidth": 80,
    "tabWidth": "auto",
    "trailingComma": "none",
    "parser": "babylon",
    "arrowParens": "avoid"
  },
  "useEslint": false,
  "useStylelint": false,
  "useEditorConfig": true,
  "prettierEslintOptions": {
    "prettierLast": false
  }
}

**Comment by jjmax75** [comment] 2018-02-02 14:36
same

**Comment by CyrusZei** [comment] 2018-02-02 14:39
same here, It won't trigger at all

**Comment by SavePointSam** [comment] 2018-02-02 14:44
Closing as this is a duplicate of https://github.com/prettier/prettier-atom/issues/364. Thank you for reporting! I’ve posted a temporary fix in that thread until we can get a fixed build out later today. Apologies for the errors, I understand how frustrating it can be. 💙

**Closed** 2018-02-02 14:45 UTC
Labels: duplicate
