### ISSUE TITLE
Vue.js files missing some rules

### ISSUE THREAD

**Issue by RichardChaumont** [prettier/prettier-atom#155] opened 2017-05-03 14:10 UTC
I'm using this plugin with `vue.js` files. 

My code:

```
export default {
	name: 'CalendarWrapper',
	data(){
		return {
			dialogVisible: true,
			loading: true
		}
	}
}
```

If I have it inside a `.js` file it gets formated according to my rules. If I have it inside a `vue.js` file some changes are applied some are not. 

Specifically `data() {` becomes `data(){` if in a `.js` file and not otherwise.

I think the related rule is: 

    'space-before-blocks': ['error', 'never']

I'm happy to add a spec/test if you point me out if the problem is in this repo and where I find the tests (didn't find any tests).

Thanks!

**Comment by robwise** [comment] 2017-05-03 20:42
@RichardChaumont Can you use `prettier-eslint-cli` on this file and see if the same thing happens? If so, it's a bug with prettier-eslint and not this plugin.

All test files are right next to their source file with the same name except with `.test` in their extension. However, because this plugin just calls either prettier or prettier-eslint, we don't have tests that verify that check those plugins as those tests should go in their respective repos, not this one.

**Comment by RichardChaumont** [comment] 2017-05-04 05:33
@robwise thanks for feedback. `prettier-eslint-cli` is for `.js` files right? I did try it on a folder with `.vue` files and it does not run because it cannot interpretate `css` in the file. Basically `.vue` files are like `.html` files with html where the JavaScript is inside a `<script>`  tag. What plugin does `prettier-atom` use to run such files?

**Comment by robwise** [comment] 2017-05-04 05:44
If you have the eslint integration on it should use `prettier-eslint`, if you have it off, it should use `prettier`. The fact that it's embedded in script tags shouldn't change that AFAIK. It's very strange that it is giving you different results like this. I will try and reproduce locally, see what's up, and report back.

**Comment by robwise** [comment] 2017-06-29 07:58
@RichardChaumont are you still having this issue?

**Comment by robwise** [comment] 2017-06-29 08:48
I just released 0.35.0 which uses prettier 1.5. Prettier 1.5 has CSS-in-JS support. Could you see if maybe this fixes the problem?

**Comment by robwise** [comment] 2017-07-02 10:45
I am going to close this for now, please let me know if there is still something that needs to be addressed and I will reopen.

**Closed by robwise** 2017-07-02 10:45 UTC
Labels: question

**Comment by fanyer** [comment] 2017-07-07 11:24
same here. `.js` files run correctly, while `.vue` wrong.

**Comment by fanyer** [comment] 2017-07-07 11:47
In my case, all rules in `.eslintrc` works normally in `.js` files.
However, not all parts of rules in `.eslintrc` works in `.vue` files.

my `.eslintrc`:
```
{
    "extends": "eslint-config-hfe",
    "rules": {
        "semi": ["error", "never"],
        "space-before-function-paren": [2, "always"],
        "no-console": 2,
        "space-in-parens": [2, "always"],
        "quotes": [2, "single", "avoid-escape"]
    }
}

```
In `.vue` files,
`semi` rules works, while `  "space-before-function-paren": [2, "always"],` doesn't work.

**Comment by yongjun21** [comment] 2018-01-25 14:40
Encountering the same issue. Further isolated the problem. It seems it does not matter the file extension. If you take way the <script> tags, it formats correct regardless it's a .vue or a .js

**Comment by tinymachine** [comment] 2018-07-12 21:11
Env:
prettier-atom@0.54.0 (using the prettier-eslint@8.8.2 apm module)
atom: 1.28.1 x64
macOS: 10.13.6

Like @fanyer I'm seeing prettier-atom obey some rules from my `.eslintrc.js` but not others, only I'm seeing the same problem in both `.vue` and `.js` files.

prettier-atom is configured in Atom (I don't have a `.prettierrc`) using all the defaults except I've turned on "ESLint Integration" and and "Format Files on Save".

Here's my `.eslintrc.js`:
```js
module.exports = {
  rules: {
    'quote-props': ['error', 'always'], // ✗ doesn't work
    quotes: ['error', 'single'], // ✓ works (overrides prettier-atom default)
    semi: ['error', 'never'], // ✓ works (overrides prettier-atom default)
    'space-before-function-paren': ['error', 'always'] // ✗ doesn't work
  }
}
```

Thanks for any help you might be able to provide!

**Comment by robwise** [comment] 2018-07-13 05:00
Hi @tinymachine. A lot of times errors like these tend to be within the packages we are using themselves, as opposed to prettier-atom which just calls them under the hood. In your case, since you have ESlint integration enabled, we are making a call to prettier-eslint under the hood. Can you help debug by calling the prettier-eslint CLI directly and see if the same problem occurs? That will help narrow down where the problem lies.

**Comment by tinymachine** [comment] 2018-07-13 23:54
Thanks for your reply, @robwise (and for a great Atom extension). It does look like this is an issue with prettier-eslint, judging from prettier/prettier-eslint#94 (for anyone interested, see @yongjun21's [comment](https://github.com/prettier/prettier-eslint/issues/94#issuecomment-360547290)). I considered switching to VS Code and using Vetur, but it looks like it also depends on prettier-eslint and thus [suffers from the same issue](https://github.com/vuejs/vetur/issues/695), alas.

**Comment by robwise** [comment] 2018-07-14 05:19
@tinymachine If it works with just normal prettier and just normal eslint, then you can use [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier). This way you can just not use prettier-atom and instead use linter-eslint to have eslint run the prettier formatting.

**Comment by tinymachine** [comment] 2018-07-14 05:22
Thanks so much for the tip, @robwise -- I'll check that out!
