### ISSUE TITLE
.eslintrc not correctly used

### ISSUE THREAD

**Issue by theboyWhoCriedWoolf** [prettier/prettier-atom#346] opened 2018-01-07 21:41 UTC
space-before-function-paren is not correctly picked up from `.eslintrc` config and still changes the file to the wrong specification

**Comment by lindell** [comment] 2018-01-08 11:57
Duplicate of #339

**Comment by darahak** [comment] 2018-01-08 23:19
Please refer to #334.

**Closed by darahak** 2018-01-08 23:19 UTC
