### ISSUE TITLE
Opening an empty file causes prettier-atom to crash the entire application

### ISSUE THREAD

**Issue by kaiyoma** [prettier/prettier-atom#699] opened 2020-03-18 01:21 UTC
Super easy to repro. Create an empty file, then open it in Atom. Bam! The whole thing crashes. If this plugin is disabled, the file can be opened just fine.

Paste the output of the `Prettier: Debug` command below.

```
Atom version: 1.45.0
prettier-atom version: 0.58.2
prettier: bundled
prettier version: 1.18.2
prettier-eslint version: 9.0.1
prettier-atom configuration: {
  "formatOnSaveOptions": {
    "enabled": true,
    "isDisabledIfNoConfigFile": true,
    "showInStatusBar": true,
    "respectEslintignore": true,
    "excludedGlobs": [],
    "whitelistedGlobs": [],
    "isDisabledIfNotInPackageJson": false,
    "ignoreNodeModules": true
  },
  "useEslint": false,
  "useStylelint": false,
  "useEditorConfig": true,
  "prettierEslintOptions": {
    "prettierLast": false
  }
}
```

**Comment by robwise** [comment] 2020-03-31 15:51
Sorry for late response, been crazy at work with the COVID thing.

I can't repro this?

**Comment by kaiyoma** [comment] 2020-03-31 17:06
Not sure what to say, happens every time for me. If I disable the plugin, the crashing stops. ¯\_(ツ)_/¯

Any extra info I can provide?

**Comment by robwise** [comment] 2020-03-31 18:11
Can you try re-installing the plugin?

Any info from Cmd Shift I (opens a chrome-like console that might give some clues as far as error messages)?

**Comment by kaiyoma** [comment] 2020-04-01 01:55
Devtools aren't helpful here, since they detach from the main program as soon as it crashes. I checked and there aren't any messages in the console when Atom crashes.

I also tried uninstalling and reinstalling and the problem still persists.

**Comment by robwise** [comment] 2020-04-14 20:42
Shoot, yeah super hard to debug here since I can't repro. Can you try updating to latest (just released) and see if that fixes anything? Not sure why it would but not sure what else to try.

**Comment by kaiyoma** [comment] 2020-04-14 20:55
Just updated, still crashes.

**Comment by robwise** [comment] 2020-04-15 00:29
Does it close the window or just hang?

**Comment by kaiyoma** [comment] 2020-04-15 00:35
It crashes the editor pretty hard:

![image](https://user-images.githubusercontent.com/10719780/79286704-465d9400-7e76-11ea-9bd6-718a58d1bc11.png)

**Comment by robwise** [comment] 2020-04-15 19:42
Oh wow okay, hmm, I don't have a windows machine so perhaps this is specific to Windows. Does anyone else on windows reading this get this problem?

**Comment by danefitzmaurice** [comment] 2020-04-29 19:57
I can confirm this appears to be a Windows-only issue. For me, it happens when I attempt to open files that lack period character in their filename, such as the ATOM_COMMIT_EDITMSG file in my project's .git directory. This is not the case on macOS.

I was able to trace the root of the crash (in my case, at least). It starts with an attempt by the plugin to check if the opened file is formattable via `isFileFormattable`. This in turn fetches an instance of prettier and calls `getFileInfo.sync`. Ultimately, this results in a call to a function called `getInterpreter` where the crash happens right after `fs.closeSync` is invoked. 

Here's a link to the exact line in the prettier source
https://github.com/prettier/prettier/blob/ba500e22f9001107dd9150629687df878e02b1f4/src/main/options.js#L158

...and here is a stacktrace I generated at that line right before the crash occurs
```
@ getInterpreter (C:\Users\17032\.atom\packages\prettier-atom\node_modules\prettier\index.js:11533:16)
@ Object.inferParser (C:\Users\17032\.atom\packages\prettier-atom\node_modules\prettier\index.js:11551:25)
@ _getFileInfo (C:\Users\17032\.atom\packages\prettier-atom\node_modules\prettier\index.js:23496:31)
@ getFileInfo.sync (C:\Users\17032\.atom\packages\prettier-atom\node_modules\prettier\index.js:23478:10)
@ Function.args (C:\Users\17032\.atom\packages\prettier-atom\node_modules\prettier\index.js:50696:12)
@ getPrettierFileInfoForCurrentFilePath (C:\Users\17032\.atom\packages\prettier-atom\dist\helpers\isFileFormattable.js:23:41)
@ C:\Users\17032\.atom\packages\prettier-atom\node_modules\lodash\lodash.min.js:49:114
@ n (C:\Users\17032\.atom\packages\prettier-atom\node_modules\lodash\lodash.min.js:5:89)
@ C:\Users\17032\.atom\packages\prettier-atom\node_modules\lodash\lodash.min.js:51:79
@ u (C:\Users\17032\.atom\packages\prettier-atom\node_modules\lodash\lodash.min.js:5:521)
@ C:\Users\17032\.atom\packages\prettier-atom\node_modules\lodash\lodash.min.js:51:56
@ n (C:\Users\17032\.atom\packages\prettier-atom\node_modules\lodash\lodash.min.js:5:89)
@ C:\Users\17032\.atom\packages\prettier-atom\node_modules\lodash\lodash.min.js:63:257
@ updateStatusTileScope (C:\Users\17032\.atom\packages\prettier-atom\dist\statusTile\updateStatusTileScope.js:11:88)
@ subscriptions.add.atom.workspace.onDidChangeActiveTextEditor.atom.workspace.onDidChangeActiveTextEditor.editor (C:\Users\17032\.atom\packages\prettier-atom\dist\main.js:50:103)```

**Comment by danefitzmaurice** [comment] 2020-04-29 21:04
Quick follow up -- I think I know the EXACT cause now. When fs.closeSync is called in that try/catch block, the passed file descriptor has in fact already been closed from within the `readlines` instance created a few lines up. This results in a `EBADF` error that apparently Atom can't survive. I confirmed this by opening a file descriptor and then attempting to close it twice in my init script, which resulted in Atom crashing consistently upon startup.

A fix for this might necessitate a fallback for getting the needed info for determining if the file is formattable should the relevant conditions be met.

**Comment by danefitzmaurice** [comment] 2020-04-29 22:52
Finished my work for the day and had nothing better to do, so I decided to see if I could implement a local hot fix for this issue in my init script. Got it working nicely after a bit of fidgeting around.

```javascript
const path = require('path');

// Attempt to get path of prettier-atom package
const prettierAtomPath = atom.packages
  .getAvailablePackagePaths()
  .find((p) => /prettier-atom$/.test(p));

if (prettierAtomPath) {
  const distPath = path.join(prettierAtomPath, 'dist');

  const helpers = require(`${distPath}/helpers`);
  const { getCurrentFilePath } = require(`${distPath}/editorInterface`);

  // Save reference to original isFileFormattable function
  const isFileFormattable = helpers.isFileFormattable;

  // Wrap isFileFormattable in a handler that prevents prettier-atom
  // from invoking "prettier.getFileInfo.sync" on the target filepath
  // if the filename does not include an extension.
  helpers.isFileFormattable = (editor) => {
    const filename = path.basename(getCurrentFilePath(editor));

    if (!filename.includes('.')) return false;

    return isFileFormattable(editor);
  };
}
```
This wraps the existing `isFileFormattable` function in a handler that hard-sets the formattability to `false` if the target file has no extension. You could certainly modify this to make that check with an alternative to prettier's `getInterpreter ` function if you really need it.

Hope this helps anybody who was running into the same issue!

**Comment by robwise** [comment] 2021-01-22 20:50
Doing some issues clean-up. If this is still an issue, please re-open.

**Closed by robwise** 2021-01-22 20:50 UTC
Labels: troubleshooting
