### ISSUE TITLE
prettier-atom failed: Error while loading rule 'graphql/template-strings'

### ISSUE THREAD

**Issue by Sly777** [prettier/prettier-atom#248] opened 2017-08-14 22:40 UTC
## Env Info
Atom v.: 1.19.x
macosx v.: el capitan
Prettier-atom v.: 0.37.0

## Error Details
**Error Message when I try ```format``` with Prettier-atom**

```prettier-atom failed: Error while loading rule 'graphql/template-strings': Must provide .graphqlconfig file or pass in schemaJson option with schema object or schemaJsonFilepath with absolute path to the json file.```

Normally, It doesn't get any problem when I run prettier on the terminal. But If I format on other child folders of the **project root**, prettier-atom is giving that error. But If I format any file on the project root, It doesn't give any error.

To try/test the problem: https://github.com/Sly777/ran/tree/beta

## Example Codes:

.eslintrc
```json
{
  "parser": "babel-eslint",
  "env": {
    "browser": true,
    "node": true,
    "es6": true
  },
  "extends": [
    "airbnb",
    "prettier",
    "prettier/react",
    "plugin:import/warnings"
  ],
  "plugins": [
    "prettier",
    "graphql",
    "import"
  ],
  "globals": {
    "document": true,
    "window": true,
    "process": true,
    "fetch": false,
    "ANALYTICS_TRACKING_ID": false,
    "AUTH0_CLIENT_ID": false,
    "AUTH0_DOMAIN": false,
    "GRAPHQL_ENDPOINT": false,
    "NEWSLETTER_FORM_ACTION": false,
    "NEWSLETTER_FORM_INPUT_NAME": false,
    "ON_PRODUCTION": true
  },
  "rules": {
    "react/forbid-prop-types": 0,
    "react/jsx-filename-extension": 0,
    "react/react-in-jsx-scope": 0,
    "class-methods-use-this": 0,
    "no-unused-expressions": ["error", { "allowTaggedTemplates": true }],
    "no-underscore-dangle": ["error", {
      "allow": ["__REDUX_DEVTOOLS_EXTENSION_COMPOSE__"]
    }],
    "react/no-unused-prop-types": 0,
    "consistent-return": 0,
    "import/no-extraneous-dependencies": 0,
    "prettier/prettier": ["error", {
      "singleQuote": true
    }],
    "graphql/template-strings": ["error", {
      "env": "literal"
    }]
  }
}
```

.graphqlconfig
```json
{
  "schemaPath": "./libraries/graphql_schemas/schema.graphql",
  "extensions": {
    "endpoints": {
      "default": "https://api.graph.cool/simple/v1/cixmkt2ul01q00122mksg82pn"
    }
  }
}
```

**Comment by darahak** [comment] 2017-08-23 22:37
@robwise I'm not a GraphQL user. Have any clue about what's happening?

**Comment by robwise** [comment] 2017-08-24 17:01
@darahak I'm not either, unfortunately, but I figure that if it's only happening with our plugin and not when calling the prettier directly, then it's got to be a problem with what we're passing to prettier?

**Comment by darahak** [comment] 2017-08-27 14:30
@Sly777 You are probably using the ESLint integration and the problem is coming from `eslint-plugin-graphql`.

From your config:

```json
"graphql/template-strings": ["error", {
  "env": "literal"
}]
```

And it looks like some options are missing.
Here's an example from their repo:

```js
// In a file called .eslintrc.js
module.exports = {
  parser: "babel-eslint",
  rules: {
    "graphql/template-strings": ['error', {
      // Import default settings for your GraphQL client. Supported values:
      // 'apollo', 'relay', 'lokka', 'literal'
      env: 'apollo',

      // Import your schema JSON here
      schemaJson: require('./schema.json'),

      // OR provide absolute path to your schema JSON
      // schemaJsonFilepath: path.resolve(__dirname, './schema.json'),

      // OR provide the schema in the Schema Language format
      // schemaString: printSchema(schema),

      // tagName is gql by default
    }]
  },
  plugins: [
    'graphql'
  ]
}
```

**Comment by robwise** [comment] 2017-08-27 22:06
@Sly777 When you say you don't get any error when running prettier on the terminal, are you running normal prettier or prettier-eslint-cli?

**Comment by Sly777** [comment] 2017-08-28 12:57
Hey @robwise, I'm using ```eslint-plugin-prettier``` and ```eslint-config-prettier``` for mixing eslint & prettier. After that, I'm just running;
```eslint --fix --ext .gql --ext .graphql --ext .js pages components containers libraries server helper_scripts```

**Comment by robwise** [comment] 2017-08-28 17:40
@Sly777 It seems like you are using eslint-config-prettier and eslint-plugin-prettier to integrate eslint and prettier together (instead of prettier-eslint). Aren't you able to just disable the prettier-atom package and run linter-eslint's autofix?

**Comment by robwise** [comment] 2017-12-06 04:46
I am going to close this for now, please let me know if there is still something that needs to be addressed and I will reopen.

**Closed by robwise** 2017-12-06 04:46 UTC
Labels: bug
