### ISSUE TITLE
PrettierRC Config file not reloaded on change

### ISSUE THREAD

**Issue by MentalGear** [prettier/prettier-atom#867] opened 2020-08-19 09:31 UTC
First, thanks for this great atom plugin!

The issue: The prettierRC file is not reloaded by the plugin after changes are made on the rc file. This can lead to some confusing behavior, for example, when changing semi:false, yet on save, prettier is not formatting as expected.

Only after quitting and restarting atom, the new RC config is respected. Maybe the plugin could monitor the rc file for changes ?

**Comment by robwise** [comment] 2020-09-14 00:18
yeah for sure we should do, closing because dupe of https://github.com/prettier/prettier-atom/issues/270 but I agree

**Closed by robwise** 2020-09-14 00:18 UTC
