### ISSUE TITLE
Show which options are used on format

### ISSUE THREAD

**Issue by darahak** [prettier/prettier-atom#178] opened 2017-06-02 11:36 UTC
Related to #177.

Looks like `prettier-atom` is not transparent/explicit enough on which options are used for formatting and where they come from (ESLint, EditorConfig, etc.).

It's hard to debug, so we could add another toggle command that shows what the formatter is doing every time.

**Comment by robwise** [comment] 2017-08-18 14:09
We seem to be getting lots of issues that people think are bugs but are actually just due to not understanding the complex scenarios in which options will change. I think a feature like this could be really useful. Basically, we could make it so that every time we do something, we can optionally log to the console what is happening and why?

**Comment by darahak** [comment] 2017-08-18 14:42
I agree. At least as a first iteration, console logs would really help.

To take it further, I would limit the output to one message displayed as a notification or a panel (like the `Key Binding Resolver` command).
We could at least avoid having to open DevTools (can be hard to read because of traces from other packages).

Currently, I don't remember how we handle the options. I'll take a look.

**Comment by olsonpm** [comment] 2018-02-10 04:50
I thought a lot about this today and decided the goal should be to help maintainers debug the resulting issues.  I don't think there's a sensible way to provide a narrow, user friendly amount of data that will let them debug the issues themselves because the apis just don't exist for it.

The best solution I can think of then will be to add all the configurations to the debug output e.g. print the configuration resulting from prettier's `resolveConfig`, eslint's [getConfigForFile](https://eslint.org/docs/developer-guide/nodejs-api#clienginegetconfigforfile) etc.

I'd create a PR with that anyway.
<br>

In order to help users help themselves I believe the following would need to exist
- get the filepaths for each of the configurations found
- get the filepaths for each configuration property of the merged result (merged result = prettier config + eslint config + ...)
- a short explanation of how the configurations were merged.  This would be the responsibility of prettier-atom which understands that e.g. because editorconfig integration is enabled, it should print: "prettier config properties are assigned over those in the editorconfig".

**Comment by robwise** [comment] 2018-02-10 15:34
This sounds like a good plan. I would only add that it would be preferable to do this via a special debug mode only somehow so as not to spam the console under normal circumstances.

**Comment by olsonpm** [comment] 2018-02-10 16:43
i was thinking the debug command which new issues advise to copy paste so maintainers have it available.

**Comment by robwise** [comment] 2018-02-10 16:49
I wouldn't overload that command. Right now it returns a whole bunch of debug output, but it's not necessarily a debug "mode" per se.

**Comment by olsonpm** [comment] 2018-02-10 16:51
okay, should the new issue template be modified then to request the output of a new command?  Basically if users don't paste it into new issues the i don't think the output provides value

**Comment by robwise** [comment] 2018-02-10 20:43
Well, the problem is that the two things happen at different times. If you want to just log out your version of prettier, prettier-atom, etc., you need to manually do that (as we do now with the command). If you want to log out what the various options are as prettier-atom is calculating them, that needs to happen at the time you are invoking the format.

**Comment by olsonpm** [comment] 2018-02-10 21:03
i see what you mean. In my mind I was thinking the output of "debug" should be enough to debug what happens upon a format.  Do you think user's would copy paste the result of the console output after a format?  If that should be the direction then that works for me.

**Comment by robwise** [comment] 2018-02-10 21:11
Well the problem is that if you put in the debug command you're going to need to write code that duplicates all of the logic that happens when you run executePrettierOnBufferRange (such as building the prettier options, checking settings, everything) and manually ensure that this stays in sync (if we change how this works in executePrettierOnBufferRange, we would need to remember to go change how it works in the debug command as well). If you just put in some function that can `_.tap` and log values at a certain point if a certain environment or context option is set, then it's always automatically up-to-date.

**Comment by olsonpm** [comment] 2018-02-10 21:16
my idea was just to output all the configs regardless of context.  You have the prettier version and prettier-atom settings to derive everything else

**Closed** 2018-08-20 17:50 UTC
Labels: enhancement
