### ISSUE TITLE
Modifying prettierrc.js requires restart of atom to take effect.

### ISSUE THREAD

**Issue by trusktr** [prettier/prettier-atom#489] opened 2019-03-15 03:07 UTC
It'd be nice to be able to modify `.prettierrc.js` in a project and not have to restart Atom for the changes to take effect.

<details>
 <summary>Prettier: Debug</summary>

```
Atom version: 1.34.0
prettier-atom version: 0.56.2
prettier: bundled
prettier version: 1.15.2
prettier-eslint version: 8.8.2
prettier-atom configuration: {
  "formatOnSaveOptions": {
    "enabled": true,
    "showInStatusBar": true,
    "respectEslintignore": true,
    "excludedGlobs": [],
    "whitelistedGlobs": [],
    "isDisabledIfNotInPackageJson": false,
    "isDisabledIfNoConfigFile": false
  },
  "useEslint": false,
  "useStylelint": false,
  "prettierEslintOptions": {
    "prettierLast": false
  }
}
```
</details>

**Comment by robwise** [comment] 2019-03-15 17:40
Duplicate of https://github.com/prettier/prettier-atom/issues/270

**Closed by robwise** 2019-03-15 17:40 UTC
